### ISSUE TITLE
Syntax highlighting inside <script lang="ts"> sometimes breaks with template strings

### ISSUE THREAD

**Issue by Theo-Steiner** [leafOfTree/vim-svelte-plugin#18] opened 2022-04-05 03:42 UTC
Hey there, 
thank you for maintaining this plugin!
The below code seems to break syntax highlighting in everything following the closing curly braces.
```typescript
<script lang="ts">
const obj = {
    err: new Error(`${templateString}`)
};
</script>
```
It seems that it has to be both inside an object and passed as the constructor to an object for the highlighting to break.
<img width="927" alt="スクリーンショット 2022-04-05 12 37 32" src="https://user-images.githubusercontent.com/40017636/161674519-95146376-73ed-46ad-8955-c140b48ee101.png">

**Comment by leafOfTree** [comment] 2022-04-06 03:36
Hi there. Thanks for your feedback.
Actually, it seems to be a bug of TypeScript syntax `runtime/syntax/typescriptcommon` because I can reproduce it with a `.ts` file (set filetype=typescript).

Anyway, I fixed it by adding a syntax patch from our side: https://github.com/leafOfTree/vim-svelte-plugin/commit/cee02ddf99afe267ab515e53a1788050861cdd97
Please update this plugin and check if it works

![Screen Shot 2022-04-06 at 11 33 12 AM](https://user-images.githubusercontent.com/13349592/161890589-8eaf6621-79a1-47a4-ba4e-334393ca9b82.png)
.

**Comment by leafOfTree** [comment] 2023-09-25 04:36
I'm closing it. Feel free to reopen it if necessary.

**Closed as completed by leafOfTree** 2023-09-25 04:36 UTC
